routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/* set language for site starts here   */
Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale); 
    return redirect()->back();
});

/* set language for site ends here   */

Route::post('ckeditor/image_upload', 'CKEditorController@upload')->name('upload');

Route::get('/', 'MainController@index');

Route::get('admin/file-upload', 'EbookController@create');
Route::post('admin/file-upload/upload', 'EbookController@upload')->name('upload');
Route::post('admin/file-upload/store', 'EbookController@store');
Route::post('admin/file-upload/storecoverimagepdf', 'EbookController@storecoverimagepdf');
Route::post('admin/file-upload/update', 'EbookController@update'); 

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/changePassword','HomeController@showChangePasswordForm');
Route::post('/changePassword','HomeController@changePassword')->name('changePassword');


Route::get('about', 'CmsController@about');
Route::get('careers', 'CmsController@careers');
Route::get('testimonials', 'CmsController@testimonials');
Route::get('terms', 'CmsController@terms');
Route::get('privacy-policy', 'CmsController@privacy');
Route::get('help', 'CmsController@help');
Route::get('benefits', 'CmsController@benefits');
Route::get('refund-policy', 'CmsController@refund_policy');
Route::get('thank-you', 'CmsController@thank_you');


Route::get('/contact', 'ContactController@index');
Route::post('/contact', 'ContactController@store');


Route::get('/subscribe', 'SubscribeController@index')->name('subscribe');
Route::get('/subscribe-membership','SubscribeController@buyMembership');
Route::get('/subscribe-membership2','SubscribeController@buyMembership2');
Route::post('/subscribe-membership','SubscribeController@buyMembershipPost')->name('subscribe-membership');

  
Route::get('/', function () {
    return view('home');
});
Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
	Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
    Route::get('/home', 'AdminController@index')->name('admin.home');
	
	Route::resource('/users','UserController'); 
	Route::resource('/categories','CategoryController'); 
	Route::resource('/faqs','FaqController'); 
	Route::resource('/features','FeaturesController'); 
	Route::resource('/testimonials','TestimonialController');
	Route::resource('/tags','TagController');  
	Route::resource('/contents','ContentController'); 
	Route::resource('/seos','SeoController');  
	
	Route::resource('/subscribers','UserController'); 
	Route::get('/active/subscribers', 'UserController@showsubscribers_active');
	Route::get('/inactive/subscribers', 'UserController@showsubscribers_inactive');
	Route::get('subscriber_remove/{subscriber_id}','UserController@subscriber_remove');
	Route::get('inactive_subscriber_view/{subscriber_id}','UserController@inactive_subscriber_view');
	Route::get('active_subscriber_view/{subscriber_id}','UserController@active_subscriber_view');
	Route::any('/active/subscribers/change_password','UserController@change_password');
	Route::resource('/ebooks','EbookController'); 

});

Route::get('/logout',[
        'uses' => 'MainController@logout', 
        'as'   => 'logout'
        ]);
Route::get('/cancel-account', 'MainController@cancel_account');
Route::post('/cancel-account','MainController@store')->name('cancel-account');

/*Route::get('/pricing', 'MainController@pricing');
Route::post('/pricing', 'MainController@pricing_post');*/



/*Route::get('/pricing-step2', 'MainController@index')->name('pricing_step2');
Route::get('/pricing-step2','MainController@pricing_step2');
Route::post('/pricing-step2','MainController@pricing_post_step2')->name('pricing_step2');
*/
Route::get('pricing','MainController@pricing_step1');
Route::get('/pricing-step2/{plan_id}','MainController@pricing_step2');
Route::post('/pricing-step2', 'MainController@pricing_post')->name('pricing_step2');
Route::get('/', ['as'=>'home', 'uses'=>'MainController@home']);


Route::get('/view-profile','MainController@view_profile');
Route::post('/view-profile', 'MainController@update_profile')->name('update_profile');
Route::get('books','CatController@showallcategory');
Route::get('bookcategory/{category_id}','CatController@show');
Route::get('ebookview/{book_id}','CatController@ebookview');
Route::get('ebookpreview/{book_id}','PreviewController@ebookpreview');

Route::get('ebookpreview2','PreviewController@ebookpreview2');

/*********** USER Routes ************/


Route::get('dashboard','DashboardController@index');

/*********** Accounts route **********/
Route::get('accounts','AccountsController@index');
Route::get('accounts/add','AccountsController@add');
Route::post('accounts/save','AccountsController@save');
Route::get('delete_account/{id}','AccountsController@delete_account');
Route::get('show_account/{id}','AccountsController@show');
Route::get('show_account/{id}/{all}','AccountsController@show');

Route::resource('accounts','AccountsController');

/*********** Budgets route **********/

Route::get('budgets/add','BudgetsController@add');
Route::post('budgets/save','BudgetsController@save');
Route::get('budgets/show/{id}','BudgetsController@show');
Route::get('budgets/show/{id}/{all}','BudgetsController@show');

Route::get('delete_budget/{id}','BudgetsController@delete_budget');
Route::resource('budgets','BudgetsController');

/*********** Categories route **********/
Route::get('categories/add','CategoriesController@add');
Route::post('categories/save','CategoriesController@save');
Route::get('categories/show/{id}','CategoriesController@show');
Route::get('categories/show/{id}/{all}','CategoriesController@show');

 

Route::get('delete_category/{id}','CategoriesController@delete_category');
Route::resource('categories','CategoriesController');

/*********** Liabilities route **********/
Route::get('liabilities','LiabilitiesController@index');
Route::get('liabilities/add','LiabilitiesController@add');
Route::post('liabilities/save','LiabilitiesController@save');
Route::get('liabilities/show/{id}','LiabilitiesController@show');
Route::get('liabilities/show/{id}/{all}','LiabilitiesController@show');

 
Route::resource('liabilities','LiabilitiesController');
Route::get('remove_liability/{id}','LiabilitiesController@remove_liability');

/*********** Transactions route **********/
Route::get('transactions','TransactionsController@index');
Route::post('transactions','TransactionsController@index');
Route::get('transations/add','TransactionsController@add');
Route::get('repeat_option/{id}','TransactionsController@repeat_option');

Route::get('transations/show/{id}','TransactionsController@show');

Route::get('repeat_month_day/{id}','TransactionsController@repeat_month_day');
Route::get('clone_transaction/{id}','TransactionsController@clone_transaction');
Route::get('stop_repeated_transections/{id}','TransactionsController@stop_repeated_transections');
Route::get('remove_transaction/{id}','TransactionsController@remove_transaction');
Route::post('transactions/save','TransactionsController@save');
Route::post('transactions/search','TransactionsController@search');
 
Route::resource('transactions','TransactionsController');
//Route::resource('/categories','CategoryController'); 
 
Auth::routes();

 

/******************************/
Route::get('budget_cron','CronController@manage_budgets');
Route::get('create_transection','CronController@create_transection');
 

/* language translator manager url rewriting starts here */
Route::get('/admin/translations/view/{groupKey?}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@getView']);
Route::get('/admin/translations/{groupKey?}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@getIndex']);
Route::post('/admin/translations/add/{groupKey}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postAdd']);
Route::post('/admin/translations/edit/{groupKey}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postEdit']); 
Route::post('/admin/translations/delete/{groupKey}/{translationKey}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postDelete']);
Route::post('/admin/translations/import',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postImport']);
Route::post('/admin/translations/find',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postFind']);
Route::post('/admin/translations/locales/add',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postAddLocale']);
Route::post('/admin/translations/locales/remove',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postRemoveLocale']);
Route::post('/admin/translations/publish/{groupKey}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postPublish']);
Route::post('/admin/translations/translate-missing',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postTranslateMissing']);
Route::post('/admin/translations/groups/add','\Barryvdh\TranslationManager\Controller@postAddGroup');

/* language translator manager url rewriting ends here */

app/Tag.php
<?php

  

namespace App;

  

use Illuminate\Database\Eloquent\Model;

   

class Tag extends Model

{

	protected $table = 'tags';
    public $fillable = [

        'name_en', 'name_fr','name_nt','name_dm','name_at','name_ge','name_sw','name_no',
		'description_en','description_fr','description_nt','description_dm','description_at',
		'description_ge','description_sw','description_no','created_on'

    ];
	public $timestamps = false;
	  
	 public function setUpdatedAt($value)

    {

      return NULL;

    }


    public function setCreatedAt($value)

    {

      return NULL;

    }
}

app/Http/Controllers/TagController.php
<?php

  

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;
use App\User; 
use DB; 
use App\Tag; 


  

class TagController extends Controller

{

    /**

     * Display a listing of the resource.

     *

     * @return \Illuminate\Http\Response

     */
	 private $apiKey; 
	 
	 public function __construct()
    {
		$this->apiKey = "Category";
        $this->middleware('auth:admin'); 
    } 

    public function index()

    {
	 
	 	 
	 
        $tags = Tag::orderBy('created_on', 'desc')->paginate(10);
 
        return view('tags.index',compact('tags'))
			->with(['MainTitle'=>$this->apiKey])
            ->with('i', (request()->input('page', 1) - 1) * 5);

    }

   

    /**

     * Show the form for creating a new resource.

     *

     * @return \Illuminate\Http\Response

     */

    public function create()

    {

        return view('tags.create');

    }

  

    /**

     * Store a newly created resource in storage.

     *

     * @param  \Illuminate\Http\Request  $request

     * @return \Illuminate\Http\Response

     */

    public function store(Request $request)

    {

        $request->validate([

            'name_en' => 'required',

            'name_fr' => 'required',
			
			'name_nt' => 'required',
			
			'name_dm' => 'required',
			
			'name_at' => 'required',
			
			'name_ge' => 'required',
			
			'name_sw' => 'required',
			
			'name_no' => 'required',
					

        ]);

 		$created_on=date("Y-m-d H:i:s");
		
		
        Tag::create(array_merge($request->all(),['created_on' => $created_on]));

   		 

        return redirect()->route('tags.index')

                        ->with('success','Tag created successfully.');

    }

   

    /**

     * Display the specified resource.

     *

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function show(Tag $tag)

    {

        return view('tags.show',compact('tag'));

    }

   

    /**

     * Show the form for editing the specified resource.

     *

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function edit(Tag $tag)

    {

        return view('tags.edit',compact('tag'));

    }

  

    /**

     * Update the specified resource in storage.

     *

     * @param  \Illuminate\Http\Request  $request

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function update(Request $request, Tag $tag)

    {

        $request->validate([

            'name_en' => 'required',

            'name_fr' => 'required',
			
			'name_nt' => 'required',
			
			'name_dm' => 'required',
			
			'name_at' => 'required',
			
			'name_ge' => 'required',
			
			'name_sw' => 'required',
			
			'name_no' => 'required',
					

        ]);

  		

        $tag->update($request->all());

  

        return redirect()->route('tags.index')

                        ->with('success','Tag updated successfully');

    }

  

    /**

     * Remove the specified resource from storage.
 
     *

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function destroy(Tag $tag)

    {

        $tag->delete();

  

        return redirect()->route('tags.index')

                        ->with('success','Tag deleted successfully');

    }

}

resources/views/tags/create.blade.php
@extends('layouts.admin')

  

@section('content')

<div class="row">

    <div class="col-lg-12 margin-tb">

        <div class="pull-left">

            <h2>Add New Tag</h2>

        </div>

        <div class="pull-right">

            <a class="btn btn-primary-edit" href="{{ route('tags.index') }}"> Back</a>

        </div>

    </div>

</div>

   

@if ($errors->any())

    <div class="alert alert-danger">

        <strong>Whoops!</strong> There were some problems with your input.<br><br>

        <ul>

            @foreach ($errors->all() as $error)

                <li>{{ $error }}</li>

            @endforeach

        </ul>

    </div>

@endif

   

<form action="{{ route('tags.store') }}" method="POST">

    @csrf

  

     <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (English):</strong>

                <input type="text" name="name_en" class="form-control" placeholder="Name (English)" value="{{ old('name_en') }}">

            </div>

        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (France):</strong>

                <input type="text" name="name_fr" class="form-control" placeholder="Name (France)" value="{{ old('name_fr') }}">

            </div>

        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (Netherlands):</strong>

                <input type="text" name="name_nt" class="form-control" placeholder="Name (Netherlands)" value="{{ old('name_nt') }}">

            </div>

        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (Denmark):</strong>

                <input type="text" name="name_dm" class="form-control" placeholder="Name (Denmark)" value="{{ old('name_dm') }}">

            </div>

        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (Austria):</strong>

                <input type="text" name="name_at" class="form-control" placeholder="Name (Austria)" value="{{ old('name_at') }}">

            </div>

        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (Germany):</strong>

                <input type="text" name="name_ge" class="form-control" placeholder="Name (Germany)" value="{{ old('name_ge') }}">

            </div>

        </div>
        
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (Sweden):</strong>

                <input type="text" name="name_sw" class="form-control" placeholder="Name (Sweden)" value="{{ old('name_sw') }}">

            </div>

        </div>
        
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (Norway):</strong>

                <input type="text" name="name_no" class="form-control" placeholder="Name (Norway)" value="{{ old('name_no') }}">

            </div>

        </div>
        
        
        
        
         
        
        
        
         
        
         

         
        
         

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

                <button type="submit" class="btn btn-primary-edit" style="width: 100px; height: 40px;">Submit</button>

        </div>

    </div>

   

</form>

@endsection

resources/views/tags/edit.blade.php
@extends('layouts.admin')

   

@section('content')

    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Edit Tag</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-success" href="{{ route('tags.index') }}"> Back</a>

            </div>

        </div>

    </div>

   

    @if ($errors->any())

        <div class="alert alert-danger">

            <strong>Whoops!</strong> There were some problems with your input.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif

  

    <form action="{{ route('tags.update',$tag->id) }}" method="POST">

        @csrf

        @method('PUT')

   

         <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (English):</strong>

                <input type="text" name="name_en" class="form-control"  value="{{ $tag->name_en }}">

            </div>

        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (France):</strong>

                <input type="text" name="name_fr" class="form-control"  value="{{ $tag->name_fr }}">

            </div>

        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (Netherlands):</strong>

                <input type="text" name="name_nt" class="form-control"  value="{{ $tag->name_nt }}">

            </div>

        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (Denmark):</strong>

                <input type="text" name="name_dm" class="form-control"  value="{{ $tag->name_dm }}">

            </div>

        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (Austria):</strong>

                <input type="text" name="name_at" class="form-control"  value="{{ $tag->name_at }}">

            </div>

        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (Germany):</strong>

                <input type="text" name="name_ge" class="form-control"  value="{{ $tag->name_ge }}">

            </div>

        </div>
        
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (Sweden):</strong>

                <input type="text" name="name_sw" class="form-control"  value="{{ $tag->name_sw }}">

            </div>

        </div>
        
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (Norway):</strong>

                <input type="text" name="name_no" class="form-control"  value="{{ $tag->name_no }}">

            </div>

        </div>
            
             
        
         
        
         

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">

              <button type="submit" class="btn btn-primary-edit" style="width: 100px; height: 40px;">Submit</button>

            </div>

        </div>

   

    </form>

@endsection

resources/views/tags/index.blade.php
@extends('layouts.admin')

 
 
@section('content')

    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Tags</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-success" href="{{ route('tags.create') }}"> Create New Tag</a>

            </div>

        </div>

    </div>

   

    @if ($message = Session::get('success'))

        <div class="alert alert-success">

            <p>{{ $message }}</p>

        </div>

    @endif

   

    <table class="table table-bordered">

        <tr>

            <th width="5%">No</th>

            <th width="15%">Name (English)</th>
            
            <th width="15%">Name (France)</th>
            
            <th width="15%">Name (Netherlands)</th>


            
            <th width="13%">Created Date</th>
            
            <th width="13%">Mofified Date</th>

            <th width="15%">Action</th>

        </tr>

        @foreach ($tags as $tag)

        <tr>

            <td>{{ ++$i }}</td>

            <td>{{ $tag->name_en }}</td>

            <td>{{ $tag->name_fr }}</td>
            
            <td>{{ $tag->name_nt }}</td>
            
            
            
            <td>{{date('m-d-Y', strtotime($tag->created_on))}}</td>
            
            <td>
             @if(isset($tag->modified_on)  && !empty($tag->modified_on))
            	
             @else
                  &nbsp;
             @endif
            </td>

            <td>

                <form action="{{ route('tags.destroy',$tag->id) }}" method="POST">

   


    

                    <a  class="btn btn-success" href="{{ route('tags.edit',$tag->id) }}">Edit</a>

   

                    @csrf

                    @method('DELETE')

      

                    <button type="submit" class="btn btn-danger">Delete</button>

                </form>

            </td>

        </tr>

        @endforeach

    </table>

  

 {!! $tags->links() !!}

      

@endsection

resources/views/tags/layout.blade.php
<!DOCTYPE html>
    <html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>

        <!-- Fonts -->
        <link rel="dns-prefetch" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body>
        <div id="app">
            <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
                <div class="container">
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                    <a class="navbar-brand" href="{{ url('/admin/categories') }}" style="font-size:14px;">
                    Categories
                	</a>
                    <a class="navbar-brand" href="{{ url('/admin/users') }}" style="font-size:14px;">
                    Users
                	</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- Left Side Of Navbar -->
                        <ul class="navbar-nav mr-auto">

                        </ul>

                        <!-- Right Side Of Navbar -->
                        <ul class="navbar-nav ml-auto">
                            <!-- Authentication Links -->
                           <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    Admin <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            <main class="py-4" style="width: 80%;margin-left: 10%;">
                @yield('content')
            </main>
        </div>
    </body>
    </html>

resources/views/tags/show.blade.php
@extends('categories.layout')


@section('content')

    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2> Show Category</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('categories.index') }}"> Back</a>

            </div>

        </div>

    </div>

   

    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (En):</strong>

                {{ $category->name_en }}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (Fr):</strong>

                {{ $category->name_fr }}

            </div>

        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (Sp):</strong>

                {{ $category->name_sp }}

            </div>

        </div>
        
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Type:</strong>

                {{ $category->type }}

            </div>

        </div>

    </div>

@endsection