routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/* set language for site starts here   */
Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale); 
    return redirect()->back();
});

/* set language for site ends here   */

Route::post('ckeditor/image_upload', 'CKEditorController@upload')->name('upload');

Route::get('/', 'MainController@index');

Route::get('admin/file-upload', 'EbookController@create');
Route::post('admin/file-upload/upload', 'EbookController@upload')->name('upload');
Route::post('admin/file-upload/store', 'EbookController@store');
Route::post('admin/file-upload/storecoverimagepdf', 'EbookController@storecoverimagepdf');
Route::post('admin/file-upload/update', 'EbookController@update'); 

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/changePassword','HomeController@showChangePasswordForm');
Route::post('/changePassword','HomeController@changePassword')->name('changePassword');


Route::get('about', 'CmsController@about');
Route::get('careers', 'CmsController@careers');
Route::get('testimonials', 'CmsController@testimonials');
Route::get('terms', 'CmsController@terms');
Route::get('privacy-policy', 'CmsController@privacy');
Route::get('help', 'CmsController@help');
Route::get('benefits', 'CmsController@benefits');
Route::get('refund-policy', 'CmsController@refund_policy');
Route::get('thank-you', 'CmsController@thank_you');


Route::get('/contact', 'ContactController@index');
Route::post('/contact', 'ContactController@store');


Route::get('/subscribe', 'SubscribeController@index')->name('subscribe');
Route::get('/subscribe-membership','SubscribeController@buyMembership');
Route::get('/subscribe-membership2','SubscribeController@buyMembership2');
Route::post('/subscribe-membership','SubscribeController@buyMembershipPost')->name('subscribe-membership');

  
Route::get('/', function () {
    return view('home');
});
Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
	Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
    Route::get('/home', 'AdminController@index')->name('admin.home');
	
	Route::resource('/users','UserController'); 
	Route::resource('/categories','CategoryController'); 
	Route::resource('/faqs','FaqController'); 
	Route::resource('/features','FeaturesController'); 
	Route::resource('/testimonials','TestimonialController');
	Route::resource('/tags','TagController');  
	Route::resource('/contents','ContentController'); 
	Route::resource('/seos','SeoController');  
	
	Route::resource('/subscribers','UserController'); 
	Route::get('/active/subscribers', 'UserController@showsubscribers_active');
	Route::get('/inactive/subscribers', 'UserController@showsubscribers_inactive');
	Route::get('subscriber_remove/{subscriber_id}','UserController@subscriber_remove');
	Route::get('inactive_subscriber_view/{subscriber_id}','UserController@inactive_subscriber_view');
	Route::get('active_subscriber_view/{subscriber_id}','UserController@active_subscriber_view');
	Route::any('/active/subscribers/change_password','UserController@change_password');
	Route::resource('/ebooks','EbookController'); 

});

Route::get('/logout',[
        'uses' => 'MainController@logout', 
        'as'   => 'logout'
        ]);
Route::get('/cancel-account', 'MainController@cancel_account');
Route::post('/cancel-account','MainController@store')->name('cancel-account');

/*Route::get('/pricing', 'MainController@pricing');
Route::post('/pricing', 'MainController@pricing_post');*/



/*Route::get('/pricing-step2', 'MainController@index')->name('pricing_step2');
Route::get('/pricing-step2','MainController@pricing_step2');
Route::post('/pricing-step2','MainController@pricing_post_step2')->name('pricing_step2');
*/
Route::get('pricing','MainController@pricing_step1');
Route::get('/pricing-step2/{plan_id}','MainController@pricing_step2');
Route::post('/pricing-step2', 'MainController@pricing_post')->name('pricing_step2');
Route::get('/', ['as'=>'home', 'uses'=>'MainController@home']);


Route::get('/view-profile','MainController@view_profile');
Route::post('/view-profile', 'MainController@update_profile')->name('update_profile');
Route::get('books','CatController@showallcategory');
Route::get('bookcategory/{category_id}','CatController@show');
Route::get('ebookview/{book_id}','CatController@ebookview');
Route::get('ebookpreview/{book_id}','PreviewController@ebookpreview');

Route::get('ebookpreview2','PreviewController@ebookpreview2');

/*********** USER Routes ************/


Route::get('dashboard','DashboardController@index');

/*********** Accounts route **********/
Route::get('accounts','AccountsController@index');
Route::get('accounts/add','AccountsController@add');
Route::post('accounts/save','AccountsController@save');
Route::get('delete_account/{id}','AccountsController@delete_account');
Route::get('show_account/{id}','AccountsController@show');
Route::get('show_account/{id}/{all}','AccountsController@show');

Route::resource('accounts','AccountsController');

/*********** Budgets route **********/

Route::get('budgets/add','BudgetsController@add');
Route::post('budgets/save','BudgetsController@save');
Route::get('budgets/show/{id}','BudgetsController@show');
Route::get('budgets/show/{id}/{all}','BudgetsController@show');

Route::get('delete_budget/{id}','BudgetsController@delete_budget');
Route::resource('budgets','BudgetsController');

/*********** Categories route **********/
Route::get('categories/add','CategoriesController@add');
Route::post('categories/save','CategoriesController@save');
Route::get('categories/show/{id}','CategoriesController@show');
Route::get('categories/show/{id}/{all}','CategoriesController@show');

 

Route::get('delete_category/{id}','CategoriesController@delete_category');
Route::resource('categories','CategoriesController');

/*********** Liabilities route **********/
Route::get('liabilities','LiabilitiesController@index');
Route::get('liabilities/add','LiabilitiesController@add');
Route::post('liabilities/save','LiabilitiesController@save');
Route::get('liabilities/show/{id}','LiabilitiesController@show');
Route::get('liabilities/show/{id}/{all}','LiabilitiesController@show');

 
Route::resource('liabilities','LiabilitiesController');
Route::get('remove_liability/{id}','LiabilitiesController@remove_liability');

/*********** Transactions route **********/
Route::get('transactions','TransactionsController@index');
Route::post('transactions','TransactionsController@index');
Route::get('transations/add','TransactionsController@add');
Route::get('repeat_option/{id}','TransactionsController@repeat_option');

Route::get('transations/show/{id}','TransactionsController@show');

Route::get('repeat_month_day/{id}','TransactionsController@repeat_month_day');
Route::get('clone_transaction/{id}','TransactionsController@clone_transaction');
Route::get('stop_repeated_transections/{id}','TransactionsController@stop_repeated_transections');
Route::get('remove_transaction/{id}','TransactionsController@remove_transaction');
Route::post('transactions/save','TransactionsController@save');
Route::post('transactions/search','TransactionsController@search');
 
Route::resource('transactions','TransactionsController');
//Route::resource('/categories','CategoryController'); 
 
Auth::routes();

 

/******************************/
Route::get('budget_cron','CronController@manage_budgets');
Route::get('create_transection','CronController@create_transection');
 

/* language translator manager url rewriting starts here */
Route::get('/admin/translations/view/{groupKey?}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@getView']);
Route::get('/admin/translations/{groupKey?}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@getIndex']);
Route::post('/admin/translations/add/{groupKey}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postAdd']);
Route::post('/admin/translations/edit/{groupKey}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postEdit']); 
Route::post('/admin/translations/delete/{groupKey}/{translationKey}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postDelete']);
Route::post('/admin/translations/import',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postImport']);
Route::post('/admin/translations/find',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postFind']);
Route::post('/admin/translations/locales/add',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postAddLocale']);
Route::post('/admin/translations/locales/remove',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postRemoveLocale']);
Route::post('/admin/translations/publish/{groupKey}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postPublish']);
Route::post('/admin/translations/translate-missing',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postTranslateMissing']);
Route::post('/admin/translations/groups/add','\Barryvdh\TranslationManager\Controller@postAddGroup');

/* language translator manager url rewriting ends here */

app/Http/Controllers/UserController.php
<?php

  

namespace App\Http\Controllers;

  

use App\User; 

use Auth;

use DB; 

use Illuminate\Support\Facades\Hash;

use Illuminate\Http\Request;

  

class UserController extends Controller

{
 
    /**

     * Display a listing of the resource.

     *

     * @return \Illuminate\Http\Response

     */
	 private $apiKey; 
	 
	  
	public function __construct()
    {
	
		 
		  
         $this->middleware('auth:admin'); 
    }
	
    public function index()

    {
	 
	 	 
		if(Auth::guard('admin')->check())
		{  
	 	
		$users = \DB::table('users')
    ->select(
        'users.id',
        'name',
		'email',
		'created_at'
    )
    ->whereNotExists( function ($query){
        $query->select(DB::raw(1))
        ->from('user_membership')
        ->whereRaw('users.id = user_membership.user_id');
    })->orderBy('users.id', 'desc')->paginate(10);
	
	 
	
	 
 		 
 
        return view('users.index',compact('users'))
			->with(['MainTitle'=>$this->apiKey])
            ->with('i', (request()->input('page', 1) - 1) * 5);
		}
		else
		{
		return redirect('admin/login');
		}

    }
	
	
	public function subscriber_remove($subscriber_id)
	{
	
	$unsubscribe_date=date("Y-m-d H:i:s");
	DB::table('user_membership')
			->where('id', $subscriber_id)
			->update([
				'status' => 'inactive',
				'unsubscribe_date' => $unsubscribe_date
			
			]
			);
	return redirect()->action('UserController@showsubscribers_active')->with('success', 'User  unsubscribed successfully!!!');
 	}
	
	
	public function inactive_subscriber_view($subscriber_id)
	{
	
	 $subscribers = DB::select("select * from users left join user_membership on  user_membership.user_id=users.id   where user_membership.id=".$subscriber_id." order by users.id desc");
	 $countrydata = DB::select('select * from apps_countries ');
	 return view('users.viewinactive',['user'=>$subscribers[0],'countrydata'=>$countrydata]);
	//return redirect()->action('UserController@showsubscribers_active')->with('success', 'User  unsubscribed successfully!!!');
 	}
	
	public function active_subscriber_view($subscriber_id) 
	{
	
	 $subscribers = DB::select("select * from users left join user_membership on  user_membership.user_id=users.id   where user_membership.id=".$subscriber_id." order by users.id desc");
 	 $countrydata = DB::select('select * from apps_countries ');
	 return view('users.viewactive',['user'=>$subscribers[0],'countrydata'=>$countrydata,'subscriber_id'=>$subscriber_id]);
	//return redirect()->action('UserController@showsubscribers_active')->with('success', 'User  unsubscribed successfully!!!');
 	}
	
	public function showsubscribers_active()

    { 
	 
	 	 
		if(Auth::guard('admin')->check())
		{  
	 	
		 
		$subscribers = DB::table('users')
                ->join('user_membership', 'user_id', '=', 'users.id')
				->where('user_membership.status', '=', 'active')
                ->select('users.*', 'user_membership.*')
                ->orderby('users.id', 'desc')
                ->paginate(10);
		 
		 
 
        return view('users.activesubscribers',compact('subscribers'))
			->with(['MainTitle'=>$this->apiKey])
            ->with('i', (request()->input('page', 1) - 1) * 5);
		}
		else
		{
		return redirect('admin/login');
		}

    }
	
	
	public function showsubscribers_inactive()

    {
	 
	 	 
		if(Auth::guard('admin')->check())
		{  
	 	
		 
		$subscribers = DB::table('users')
                ->join('user_membership', 'user_id', '=', 'users.id')
				->where('user_membership.status', '=', 'inactive')
                ->select('users.*', 'user_membership.*')
				->orderby('users.id', 'desc')
                ->paginate(10);
		 
		 
		 
 
        return view('users.inactivesubscribers',compact('subscribers'))
			->with(['MainTitle'=>$this->apiKey])
            ->with('i', (request()->input('page', 1) - 1) * 5);
		}
		else
		{
		return redirect('admin/login');
		}

    }

   

    /**

     * Show the form for creating a new resource.

     *

     * @return \Illuminate\Http\Response

     */

    public function create()

    {

        return view('users.create');

    }

  

    /**

     * Store a newly created resource in storage.

     *

     * @param  \Illuminate\Http\Request  $request

     * @return \Illuminate\Http\Response

     */
	public function change_password()
	{
	 
		if($_POST['password']!="")
		{
		$trackings = DB::select("select * from user_membership where id=".$_POST['subscriber_id']."");
		$user_id=$trackings[0]->user_id;
				DB::table('users')
				->where('id', $user_id) 
				->update([
					'password' => Hash::make($_POST['password'])
				
				]
				);
		return redirect()->action('UserController@active_subscriber_view', ['subscriber_id' => $_POST['subscriber_id']])->with('success', 'Password changes successfully!!!');	
		}
		else
		{
		return redirect()->action('UserController@active_subscriber_view', ['subscriber_id' => $_POST['subscriber_id']]);	
		}	
	}
    public function store(Request $request)

    {

        $request->validate([

            'name' => 'required',

            'email' => 'required',
			
			'password' => 'required',
			

        ]);

 		$created_on=date("Y-m-d H:i:s");
		
		 User::create([
            'name' => $request['name'],
            'email' => $request['email'],
            'password' => Hash::make($request['password']),
        ]);
        

   

        return redirect()->route('users.index')

                        ->with('success','Users created successfully.');

    }

   

    /**

     * Display the specified resource.

     *

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function show(User $user)

    {

        return view('users.show',compact('user'));

    }

   

    /**

     * Show the form for editing the specified resource.

     *

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function edit(User $user)

    {
		
		$countrydata = DB::select('select * from apps_countries '); 	
        return view('users.edit',['user'=>$user,'countrydata'=>$countrydata]);

    }

  

    /**

     * Update the specified resource in storage.

     *

     * @param  \Illuminate\Http\Request  $request

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function update(Request $request, User $user)

    {

        $request->validate([

            'name' => 'required',

            'email' => 'required',
			

        ]);

  		

 		$user->update(array_merge($request->all(),['password' => Hash::make($_POST['password'])]));

  

        return redirect()->route('users.index')

                        ->with('success','User updated successfully');

    }

  

    /**

     * Remove the specified resource from storage.

     *

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function destroy(User $user)

    {

        $user->delete();

  

        return redirect()->route('users.index')

                        ->with('success','User deleted successfully');

    }

}

resources/views/users/budgets/budget.blade.php
@extends('layouts.app')
@section('content')

<div class="container 11">
     
</div>
<template>
<component :is="'style'">
body{background:#f6f6f6}
</component>
</template>

<div class="page dashboardpages"> 
<div class="inner-container">
<script  type="application/javascript">
var isMobile = {
    Android: function() {
        return navigator.userAgent.match(/Android/i);
    },
    BlackBerry: function() {
        return navigator.userAgent.match(/BlackBerry/i);
    },
    iOS: function() {
        return navigator.userAgent.match(/iPhone|iPad|iPod/i);
    },
    Opera: function() {
        return navigator.userAgent.match(/Opera Mini/i);
    },
    Windows: function() {
        return navigator.userAgent.match(/IEMobile/i);
    },
    any: function() {
        return (isMobile.Android() || isMobile.BlackBerry() || isMobile.iOS() || isMobile.Opera() || isMobile.Windows());
    }
};

if(isMobile.any()) {
     
     $(document).on('click', '#cat_title_ebook', function(event){
   			$('.show_hide_cat_div').toggleClass("hideCatClass"); 
 			
      		event.stopImmediatePropagation();
	});
     
}
 
  
</script>
 			 
		<div class="category-sidebar">
		 @include('layouts.sidebar')
		</div>
		<div class="category innerright-side">
				
                <div class="page-title">
				<h1> {!!html_entity_decode(__('budgets.title'))!!}</h1> 
                <a class="btn btn-success purple-btn" href="{{ env('APP_URL') }}budgets/add">{!!html_entity_decode(__('budgets.add_budget'))!!}</a>
                 </div>
                  <div class="dashborad-about">
				 <p>{!!html_entity_decode(__('budgets.listing_heading_text'))!!}</p>
                 </div>
                 
                 <div class="flashmessage">
				  @include('flash-message')
				  </div>
                  
                  <div class="dashbaordchart">
				  <h2>{!!html_entity_decode(__('budgets.total_available_budget'))!!} {!!html_entity_decode(__('common.currency_symbol'))!!} {{$total_budget}}
					<p style="margin:0;">{!!html_entity_decode(__('budgets.between'))!!} {{$month_date}}</p>
				  </h2>
				  
				  <div class="progress">
				  <div class="progress-bar" style="width:{{$pct_spent}}%"></div>
				</div>
				<p> {!!html_entity_decode(__('budgets.spent'))!!} {!!html_entity_decode(__('common.currency_symbol'))!!} {{$total_spent}} </p>
				</div>				 
                 
                 
                 
                 <div class="dashboard-recenttable">
                 
                  <div id="no-more-tables"> 
                 <table class="table table-bordered" style="margin-top:10px;">

		<thead>
        <tr>
            <th>{!!html_entity_decode(__('budgets.name'))!!} </th>
			<th>{!!html_entity_decode(__('budgets.budget_amount'))!!}</th>
			<th>{!!html_entity_decode(__('budgets.budget_type'))!!}</th>
			<th>{!!html_entity_decode(__('budgets.spent'))!!}</th>
			<th>{!!html_entity_decode(__('budgets.left'))!!}</th>
			<th>{!!html_entity_decode(__('budgets.status'))!!}</th>
			<th>{!!html_entity_decode(__('budgets.action'))!!}</th>

        </tr>
		 </thead>
        @foreach ($budgets as $budget)

        <tr>


            <td data-title="{!!html_entity_decode(__('budgets.name'))!!}"><a href="{{ env('APP_URL') }}budgets/show/{{$budget->id}}">{{ $budget->name }}</a></td>
			<td data-title="{!!html_entity_decode(__('budgets.budget_amount'))!!}">{!!html_entity_decode(__('common.currency_symbol'))!!}{{ $budget->budget_amount }} </td>
			<td data-title="{!!html_entity_decode(__('budgets.budget_type'))!!}"> {{ $budget->budget_period_name }} </td>
			
			<td data-title="{!!html_entity_decode(__('budgets.spent'))!!}">{!!html_entity_decode(__('common.currency_symbol'))!!}{{ $budget->amount_spent }} </td>
			<td data-title="{!!html_entity_decode(__('budgets.left'))!!}">{!!html_entity_decode(__('common.currency_symbol'))!!}{{ $budget->amount_left }} </td>
			 
			<td data-title="{!!html_entity_decode(__('budgets.status'))!!}">
			@if($budget->is_active ==1)
				{!!html_entity_decode(__('budgets.active'))!!}
			@else
				{!!html_entity_decode(__('budgets.inactive'))!!}
			@endif
			 
            <td data-title="{!!html_entity_decode(__('budgets.action'))!!}"> 
			<form action="{{ route('budgets.destroy',$budget->id) }}" method="POST"></form>
			<a  class="btn btn-success editicon" href="{{ route('budgets.edit',$budget->id) }}">{!!html_entity_decode(__('budgets.edit'))!!}</a>
			@csrf
			@method('DELETE')
			 
			<a  class="btn btn-success deleteicon" onclick="return confirm('{!!html_entity_decode(__('budgets.delete_confirm'))!!}')"  href="{{ env('APP_URL') }}delete_budget/{{$budget->id }}">{!!html_entity_decode(__('budgets.delete'))!!}</a>

            </td>

        </tr>

        @endforeach

    </table>
								 
</div>
		</div> 
		</div> 
    			 
    
   
    
    <div class="clear"></div>
    </div>
</div>
@endsection
 

resources/views/users/budgets/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container 11">
     
</div>
<template>
<component :is="'style'">
body{background:#f6f6f6}
</component>
</template>

<div class="page dashboardpages"> 
<div class="inner-container">
<script  type="application/javascript">
var isMobile = {
    Android: function() {
        return navigator.userAgent.match(/Android/i);
    },
    BlackBerry: function() {
        return navigator.userAgent.match(/BlackBerry/i);
    },
    iOS: function() {
        return navigator.userAgent.match(/iPhone|iPad|iPod/i);
    },
    Opera: function() {
        return navigator.userAgent.match(/Opera Mini/i);
    },
    Windows: function() {
        return navigator.userAgent.match(/IEMobile/i);
    },
    any: function() {
        return (isMobile.Android() || isMobile.BlackBerry() || isMobile.iOS() || isMobile.Opera() || isMobile.Windows());
    }
};

if(isMobile.any()) {

	
   //some code...
   //$(".show_hide_cat_div").css("display", "none");
   
 
    
     $(document).on('click', '#cat_title_ebook', function(event){
 			
 			 
  			$('.show_hide_cat_div').toggleClass("hideCatClass"); 
 			
      		event.stopImmediatePropagation();
	});
     
}
 

</script>
 			 
		<div class="category-sidebar">
		 @include('layouts.sidebar')
		 </div>
		<div class="category innerright-side">
				<div class="page-title">
                <h1> {!!html_entity_decode(__('budg_detail.page_title'))!!} </h1> 
               <a class="btn btn-success purple-btn" href="{{route('budgets.index') }}"> {!!html_entity_decode(__('common.back'))!!}</a>
		</div>

				 <div class="dashborad-about">
				 <p>{!!html_entity_decode(__('budg_detail.heading_text'))!!}  {{$budget->name}} {!!html_entity_decode(__('common.between'))!!} {{$month_date}}</p>
				 </div>
				 
			<!--<div class="chart-container">
				<div class="pie-chart-container">
				 <canvas id="line-chart" width="800" height="450"></canvas>
				</div>
			  </div>  -->
				 
                 <div class="flashmessage">
				  @include('flash-message')
			</div>

				 <div class="dashboard-recenttable">
				<div id="no-more-tables">
                <table class="table table-bordered">

			<thead>
            <tr>


				<th>{!!html_entity_decode(__('transactions.title'))!!} </th>
				<th>{!!html_entity_decode(__('transactions.amount'))!!}</th>
				<th>{!!html_entity_decode(__('transactions.account'))!!}</th>
				<th>{!!html_entity_decode(__('transactions.trans_type'))!!}</th>
				<th>{!!html_entity_decode(__('transactions.category'))!!}</th> 
				<!--<th>{!!html_entity_decode(__('transactions.budget'))!!}</th>-->
				<th>{!!html_entity_decode(__('transactions.date'))!!}</th>
				<th>{!!html_entity_decode(__('transactions.action'))!!}</th>

			</tr>
		 </thead>
        @foreach ($transactions as $trans)

        <tr>


            <td data-title="{!!html_entity_decode(__('transactions.title'))!!}" >{{ $trans->title }}</td>
			<td data-title="{!!html_entity_decode(__('transactions.amount'))!!}" >{!!html_entity_decode(__('common.currency_symbol'))!!}{{ $trans->trans_amount }} </td>
			<td data-title="{!!html_entity_decode(__('transactions.account'))!!}"> 
				@if($trans->transaction_type == 'EXPENCES')
				{{$trans->trans_account}} 
				@elseif($trans->transaction_type == 'REVENUE')
				{{$trans->trans_destini}}
				@elseif($trans->transaction_type == 'TRANSFER')
				{{$trans->trans_account}}->{{$trans->trans_destini}}
				@endif
			</td>
			<td data-title="{!!html_entity_decode(__('transactions.trans_type'))!!}">{{ $trans->transaction_type }}</td>
			<!--<td>{{ $trans->trans_cat }}</td>-->
			<td data-title="{!!html_entity_decode(__('transactions.category'))!!}"> {{$trans->budget_name}}</td>
			<td data-title="{!!html_entity_decode(__('transactions.date'))!!}"> {{ $trans->trans_date }}</td>
			
		 
			 
			 
			 
            <td data-title="{!!html_entity_decode(__('transactions.action'))!!}"> 
			 
			<a  class="btn btn-success editicon" href="{{ route('transactions.edit',$trans->id) }}">{!!html_entity_decode(__('transactions.edit'))!!}</a>
			<a  class="btn btn-success cloneicon" onclick="return confirm('{!!html_entity_decode(__('transactions.copy_confirm'))!!}')" href="{{ env('APP_URL') }}clone_transaction/{{ $trans->id}}">{!!html_entity_decode(__('transactions.clone'))!!}</a>
			<a  class="btn btn-success deleteicon" onclick="return confirm('{!!html_entity_decode(__('transactions.delete_confirm'))!!}')" href="{{ env('APP_URL') }}remove_transaction/{{$trans->id }}">{!!html_entity_decode(__('transactions.delete'))!!}</a>
			 

            </td>

        </tr>

        @endforeach

    </table>
    </div>
    				</div>
    
    
				@if($all == '')				 
		<a href="{{ env('APP_URL') }}budgets/show/{{$budget->id }}/all">{!!html_entity_decode(__('common.show_all'))!!} </a>
				@else
					<a href="{{ env('APP_URL') }}budgets/show/{{$budget->id }}">{!!html_entity_decode(__('common.show_current_month'))!!}</a>
				@endif
		</div> 
    			 
    
   
    
    <div class="clear"></div>
    </div>
	 
</div>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
 <script type="application/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.js"></script>
 
<script type="application/javascript" >

$(function(){
	
	
/*	 
 
 new Chart(document.getElementById("line-chart"), {
  type: 'line',
  data: {
    labels: [1500,1600,1700,1750,1800,1850,1900,1950,1999,2050],
    datasets: [{ 
        data: [86,114,106,106,107,111,133,221,783,2478],
        label: "Africa",
        borderColor: "#3e95cd",
        fill: false
      }  
    ]
  },
  options: {
    title: {
      display: true,
      text: 'World population per region (in millions)'
    }
  }
});
*/
  });
</script>

@endsection
 
 
 

 