routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/* set language for site starts here   */
Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale); 
    return redirect()->back();
});

/* set language for site ends here   */

Route::post('ckeditor/image_upload', 'CKEditorController@upload')->name('upload');

Route::get('/', 'MainController@index');

Route::get('admin/file-upload', 'EbookController@create');
Route::post('admin/file-upload/upload', 'EbookController@upload')->name('upload');
Route::post('admin/file-upload/store', 'EbookController@store');
Route::post('admin/file-upload/storecoverimagepdf', 'EbookController@storecoverimagepdf');
Route::post('admin/file-upload/update', 'EbookController@update'); 

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/changePassword','HomeController@showChangePasswordForm');
Route::post('/changePassword','HomeController@changePassword')->name('changePassword');


Route::get('about', 'CmsController@about');
Route::get('careers', 'CmsController@careers');
Route::get('testimonials', 'CmsController@testimonials');
Route::get('terms', 'CmsController@terms');
Route::get('privacy-policy', 'CmsController@privacy');
Route::get('help', 'CmsController@help');
Route::get('benefits', 'CmsController@benefits');
Route::get('refund-policy', 'CmsController@refund_policy');
Route::get('thank-you', 'CmsController@thank_you');


Route::get('/contact', 'ContactController@index');
Route::post('/contact', 'ContactController@store');


Route::get('/subscribe', 'SubscribeController@index')->name('subscribe');
Route::get('/subscribe-membership','SubscribeController@buyMembership');
Route::get('/subscribe-membership2','SubscribeController@buyMembership2');
Route::post('/subscribe-membership','SubscribeController@buyMembershipPost')->name('subscribe-membership');

  
Route::get('/', function () {
    return view('home');
});
Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
	Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
    Route::get('/home', 'AdminController@index')->name('admin.home');
	
	Route::resource('/users','UserController'); 
	Route::resource('/categories','CategoryController'); 
	Route::resource('/faqs','FaqController'); 
	Route::resource('/features','FeaturesController'); 
	Route::resource('/testimonials','TestimonialController');
	Route::resource('/tags','TagController');  
	Route::resource('/contents','ContentController'); 
	Route::resource('/seos','SeoController');  
	
	Route::resource('/subscribers','UserController'); 
	Route::get('/active/subscribers', 'UserController@showsubscribers_active');
	Route::get('/inactive/subscribers', 'UserController@showsubscribers_inactive');
	Route::get('subscriber_remove/{subscriber_id}','UserController@subscriber_remove');
	Route::get('inactive_subscriber_view/{subscriber_id}','UserController@inactive_subscriber_view');
	Route::get('active_subscriber_view/{subscriber_id}','UserController@active_subscriber_view');
	Route::any('/active/subscribers/change_password','UserController@change_password');
	Route::resource('/ebooks','EbookController'); 

});

Route::get('/logout',[
        'uses' => 'MainController@logout', 
        'as'   => 'logout'
        ]);
Route::get('/cancel-account', 'MainController@cancel_account');
Route::post('/cancel-account','MainController@store')->name('cancel-account');

/*Route::get('/pricing', 'MainController@pricing');
Route::post('/pricing', 'MainController@pricing_post');*/



/*Route::get('/pricing-step2', 'MainController@index')->name('pricing_step2');
Route::get('/pricing-step2','MainController@pricing_step2');
Route::post('/pricing-step2','MainController@pricing_post_step2')->name('pricing_step2');
*/
Route::get('pricing','MainController@pricing_step1');
Route::get('/pricing-step2/{plan_id}','MainController@pricing_step2');
Route::post('/pricing-step2', 'MainController@pricing_post')->name('pricing_step2');
Route::get('/', ['as'=>'home', 'uses'=>'MainController@home']);


Route::get('/view-profile','MainController@view_profile');
Route::post('/view-profile', 'MainController@update_profile')->name('update_profile');
Route::get('books','CatController@showallcategory');
Route::get('bookcategory/{category_id}','CatController@show');
Route::get('ebookview/{book_id}','CatController@ebookview');
Route::get('ebookpreview/{book_id}','PreviewController@ebookpreview');

Route::get('ebookpreview2','PreviewController@ebookpreview2');

/*********** USER Routes ************/


Route::get('dashboard','DashboardController@index');

/*********** Accounts route **********/
Route::get('accounts','AccountsController@index');
Route::get('accounts/add','AccountsController@add');
Route::post('accounts/save','AccountsController@save');
Route::get('delete_account/{id}','AccountsController@delete_account');
Route::get('show_account/{id}','AccountsController@show');
Route::get('show_account/{id}/{all}','AccountsController@show');

Route::resource('accounts','AccountsController');

/*********** Budgets route **********/

Route::get('budgets/add','BudgetsController@add');
Route::post('budgets/save','BudgetsController@save');
Route::get('budgets/show/{id}','BudgetsController@show');
Route::get('budgets/show/{id}/{all}','BudgetsController@show');

Route::get('delete_budget/{id}','BudgetsController@delete_budget');
Route::resource('budgets','BudgetsController');

/*********** Categories route **********/
Route::get('categories/add','CategoriesController@add');
Route::post('categories/save','CategoriesController@save');
Route::get('categories/show/{id}','CategoriesController@show');
Route::get('categories/show/{id}/{all}','CategoriesController@show');

 

Route::get('delete_category/{id}','CategoriesController@delete_category');
Route::resource('categories','CategoriesController');

/*********** Liabilities route **********/
Route::get('liabilities','LiabilitiesController@index');
Route::get('liabilities/add','LiabilitiesController@add');
Route::post('liabilities/save','LiabilitiesController@save');
Route::get('liabilities/show/{id}','LiabilitiesController@show');
Route::get('liabilities/show/{id}/{all}','LiabilitiesController@show');

 
Route::resource('liabilities','LiabilitiesController');
Route::get('remove_liability/{id}','LiabilitiesController@remove_liability');

/*********** Transactions route **********/
Route::get('transactions','TransactionsController@index');
Route::post('transactions','TransactionsController@index');
Route::get('transations/add','TransactionsController@add');
Route::get('repeat_option/{id}','TransactionsController@repeat_option');

Route::get('transations/show/{id}','TransactionsController@show');

Route::get('repeat_month_day/{id}','TransactionsController@repeat_month_day');
Route::get('clone_transaction/{id}','TransactionsController@clone_transaction');
Route::get('stop_repeated_transections/{id}','TransactionsController@stop_repeated_transections');
Route::get('remove_transaction/{id}','TransactionsController@remove_transaction');
Route::post('transactions/save','TransactionsController@save');
Route::post('transactions/search','TransactionsController@search');
 
Route::resource('transactions','TransactionsController');
//Route::resource('/categories','CategoryController'); 
 
Auth::routes();

 

/******************************/
Route::get('budget_cron','CronController@manage_budgets');
Route::get('create_transection','CronController@create_transection');
 

/* language translator manager url rewriting starts here */
Route::get('/admin/translations/view/{groupKey?}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@getView']);
Route::get('/admin/translations/{groupKey?}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@getIndex']);
Route::post('/admin/translations/add/{groupKey}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postAdd']);
Route::post('/admin/translations/edit/{groupKey}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postEdit']); 
Route::post('/admin/translations/delete/{groupKey}/{translationKey}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postDelete']);
Route::post('/admin/translations/import',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postImport']);
Route::post('/admin/translations/find',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postFind']);
Route::post('/admin/translations/locales/add',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postAddLocale']);
Route::post('/admin/translations/locales/remove',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postRemoveLocale']);
Route::post('/admin/translations/publish/{groupKey}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postPublish']);
Route::post('/admin/translations/translate-missing',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postTranslateMissing']);
Route::post('/admin/translations/groups/add','\Barryvdh\TranslationManager\Controller@postAddGroup');

/* language translator manager url rewriting ends here */

app/Testimonial.php
<?php

  

namespace App;

  
use Illuminate\Database\Eloquent\Model;

   

class Testimonial extends Model

{

	protected $table = 'testimonials';
    public $fillable = [

        'testimonial_client_en',
		'testimonial_location_en',
		'thumbnail',
		'description_en','description_fr','description_nl','description_dk','description_at',
		'description_de','description_se','description_no','description_it','created_on'

    ];
	public $timestamps = false;
	 
	 public function setUpdatedAt($value)

    {

      return NULL;

    }


   
}

app/Http/Controllers/TestimonialController.php
<?php

  

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;
use App\User; 
use DB; 
use App\Testimonial; 


  

class TestimonialController extends Controller

{

    /**

     * Display a listing of the resource.

     *

     * @return \Illuminate\Http\Response

     */
	 private $apiKey; 
	 
	 public function __construct()
    {
		$this->apiKey = "Category";
        $this->middleware('auth:admin'); 
    } 

    public function index()
 
    {
	 
	 	 
	 
        $testimonials = Testimonial::orderBy('created_on', 'desc')->paginate(10);
 
        return view('testimonials.index',compact('testimonials'))
			->with(['MainTitle'=>$this->apiKey])
            ->with('i', (request()->input('page', 1) - 1) * 5);

    }

   

    /**

     * Show the form for creating a new resource.

     *

     * @return \Illuminate\Http\Response

     */

    public function create()

    {
		 
        return view('testimonials.create');

    }

  

    /**

     * Store a newly created resource in storage.

     *

     * @param  \Illuminate\Http\Request  $request

     * @return \Illuminate\Http\Response

     */

    public function store(Request $request)

    {

        $request->validate([

            'testimonial_client_en' => 'required',

            'testimonial_location_en' => 'required',
			
			'description_en' => 'required',
			
			'description_fr' => 'required',
			
			'description_nl' => 'required',
			
			'description_dk' => 'required',
			
			'description_at' => 'required',
			
			'description_de' => 'required',
			
			'description_se' => 'required',
			
			'description_no' => 'required',
			
			'description_it' => 'required',
					

        ]);
		
		 

 		$created_on 		= date("Y-m-d H:i:s");
		$image 				= $request->file('image');
		
		if ($image !== null) 
		{
			$input['imagename'] = time().'.'.$image->getClientOriginalExtension();
			$destinationPath 	= public_path('/images');
			$image->move($destinationPath, $input['imagename']);
			$thumbnail = $input['imagename'];
			
			//$data_arr['thumbnail'] = $thumbnail;
			 
			//$testimonial->update($request->all(),array('thumbnail' => $thumbnail));
		} 
		else
		{
			$thumbnail = '';
			//$data_arr['thumbnail'] = '';
		}
		
		
		
		
        Testimonial::create(array_merge($request->all(),['created_on' => $created_on, 'thumbnail' => $thumbnail]));

   		 

        return redirect()->route('testimonials.index')

                        ->with('success','Testimonial created successfully.');

    }

   

    /**

     * Display the specified resource.

     *

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function show(Category $category)

    {

        return view('testimonials.show',compact('category'));

    }

   

    /**

     * Show the form for editing the specified resource.

     *

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function edit(Testimonial $testimonial)

    {

        return view('testimonials.edit',compact('testimonial'));

    }

  

    /**

     * Update the specified resource in storage.

     *

     * @param  \Illuminate\Http\Request  $request

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function update(Request $request, Testimonial $testimonial)

    {

        $request->validate([

            'testimonial_client_en' => 'required',

            'testimonial_location_en' => 'required',
			
			'description_en' => 'required',
			
			'description_fr' => 'required',
			
			'description_nl' => 'required',
			
			'description_dk' => 'required',
			
			'description_at' => 'required',
			
			'description_de' => 'required',
			
			'description_se' => 'required',
			
			'description_no' => 'required',
			
			'description_it' => 'required',
					

        ]);
		
	$postdata = $_POST;
		$data_arr = array ('testimonial_client_en' => $postdata['testimonial_client_en'],

            'testimonial_location_en' => $postdata['testimonial_location_en'],
			
			'description_en' => $postdata['description_en'],
			
			'description_fr' => $postdata['description_fr'],
			
			'description_nl' => $postdata['description_nl'],
			
			'description_dk' => $postdata['description_dk'],
			
			'description_at' => $postdata['description_at'],
			
			'description_de' => $postdata['description_de'],
			
			'description_se' => $postdata['description_se'],
			
			'description_no' => $postdata['description_no'],
			
			'description_it' => $postdata['description_it']);
			
		//$created_on 		= date("Y-m-d H:i:s");
		$image 				= $request->file('image');
		 
		
		if ($image !== null) 
		{
			$input['imagename'] 	= time().'.'.$image->getClientOriginalExtension();
			$destinationPath 		= public_path('/images');
			$image->move($destinationPath, $input['imagename']);
			$thumbnail 				= $input['imagename'];
			$data_arr['thumbnail'] 	= $thumbnail;
			 
			//$testimonial->update($request->all(),array('thumbnail' => $thumbnail));
		} 
		else
		{
			//$testimonial->update($request->all());
			$data_arr['thumbnail'] = '';
		}
		
		
		$data_id = 	$testimonial->id;
		DB::table('testimonials')->where('id', $data_id)->update($data_arr);
 
        return redirect()->route('testimonials.index')

                        ->with('success','Testimonial updated successfully');

    }

  

    /**

     * Remove the specified resource from storage.

     *

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function destroy(Testimonial $testimonial)

    {

        $testimonial->delete();

  

        return redirect()->route('testimonials.index')

                        ->with('success','Testimonial deleted successfully');

    }

}

resources/views/testimonials/create.blade.php
@extends('layouts.admin')

  

@section('content')

<div class="row">

    <div class="col-lg-12 margin-tb">

        <div class="pull-left">

            <h2>Add New Testimonial</h2>

        </div>

        <div class="pull-right">

            <a class="btn btn-primary-edit" href="{{ route('testimonials.index') }}"> Back</a>

        </div>

    </div>

</div>

   

@if ($errors->any())

    <div class="alert alert-danger">

        <strong>Whoops!</strong> There were some problems with your input.<br><br>

        <ul>

            @foreach ($errors->all() as $error)

                <li>{{ $error }}</li>

            @endforeach

        </ul>

    </div>

@endif

   

<form action="{{ route('testimonials.store') }}" method="POST" enctype="multipart/form-data">

    @csrf

  

     <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Client Name:</strong>

                <input type="text" name="testimonial_client_en" class="form-control" placeholder="Client Name" value="{{ old('testimonial_client_en') }}">

            </div>

        </div>
        
         <div class="form-group">
			<label style="color: black;" >Thumbnail</label>
			<br>
			{!! Form::file('image', array('class' => 'image')) !!}
		</div>
        
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Client Designation:</strong>

                <input type="text" name="testimonial_location_en" class="form-control" placeholder="Client Designation" value="{{ old('testimonial_location_en') }}">

            </div>

        </div>
        
         
        
        
        
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description (English):</strong>

                <textarea name="description_en" id="description_en" style="width:100%">{{ old('description_en') }}</textarea>

            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description (France):</strong>

                <textarea name="description_fr" id="description_fr" style="width:100%">{{ old('description_fr') }}</textarea>

            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description (Netherlands):</strong>

                <textarea name="description_nl" id="description_nl" style="width:100%">{{ old('description_nl') }}</textarea>

            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description (Denmark):</strong>

                <textarea name="description_dk" id="description_dk" style="width:100%">{{ old('description_dk') }}</textarea>

            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description (Austria):</strong>

                <textarea name="description_at" id="description_at" style="width:100%">{{ old('description_at') }}</textarea>

            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description (Germany):</strong>

                <textarea name="description_de" id="description_de" style="width:100%">{{ old('description_de') }}</textarea>

            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description (Sweden):</strong>

                <textarea name="description_se" id="description_se" style="width:100%">{{ old('description_se') }}</textarea>

            </div>

        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description (Norway):</strong>

                <textarea name="description_no" id="description_no" style="width:100%">{{ old('description_no') }}</textarea>

            </div>

        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description (Italian):</strong>

                <textarea name="description_it" id="description_it" style="width:100%">{{ old('description_it') }}</textarea>

            </div>

        </div>
        
        
        
        
         
        
         
        
         
        
         

         
        
         

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

                <button type="submit" class="btn btn-primary-edit" style="width: 100px; height: 40px;">Submit</button>

        </div>

    </div>

   

</form>

@endsection

resources/views/testimonials/edit.blade.php
@extends('layouts.admin')

   

@section('content')

    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Edit Testimonial</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-success" href="{{ route('testimonials.index') }}"> Back</a>

            </div>

        </div>

    </div>

   

    @if ($errors->any())

        <div class="alert alert-danger">

            <strong>Whoops!</strong> There were some problems with your input.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif

  

    <form action="{{ route('testimonials.update',$testimonial->id) }}" method="POST" enctype="multipart/form-data">

        @csrf

        @method('PUT')

   

         <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Client Name:</strong>

                <input type="text" name="testimonial_client_en" class="form-control" placeholder="Client Name" value="{{ $testimonial->testimonial_client_en }}">

            </div>

        </div>
        
         <div class="form-group">
			<label style="color: black;" >Thumbnail</label>
			<br>
			@if($testimonial->thumbnail !='')
				<img src="{{asset('public/images/')}}/{{$testimonial->thumbnail}}" style="max-height:50px;" />
			@endif
			
			{!! Form::file('image', array('class' => 'image')) !!}
		</div>
        
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Client Designation:</strong>

                <input type="text" name="testimonial_location_en" class="form-control" placeholder="Client Designation" value="{{ $testimonial->testimonial_location_en }}">

            </div>

        </div>
        
         
        
        
        
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description (English):</strong>

                <textarea name="description_en" id="description_en" style="width:100%">{{ $testimonial->description_en }}</textarea>

            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description (France):</strong>

                <textarea name="description_fr" id="description_fr" style="width:100%">{{ $testimonial->description_fr }}</textarea>

            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description (Netherlands):</strong>

                <textarea name="description_nl" id="description_nl" style="width:100%">{{ $testimonial->description_nl }}</textarea>

            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description (Denmark):</strong>

                <textarea name="description_dk" id="description_dk" style="width:100%">{{ $testimonial->description_dk }}</textarea>

            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description (Austria):</strong>

                <textarea name="description_at" id="description_at" style="width:100%">{{ $testimonial->description_at }}</textarea>

            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description (Germany):</strong>

                <textarea name="description_de" id=" description_de" style="width:100%">{{ $testimonial->description_de }}</textarea>

            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description (Sweden):</strong>

                <textarea name="description_se" id="description_se" style="width:100%">{{ $testimonial->description_se }}</textarea>

            </div>

        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description (Norway):</strong>

                <textarea name="description_no" id="description_no" style="width:100%">{{ $testimonial->description_no }}</textarea>

            </div>

        </div>
        
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description (Italian):</strong>

                <textarea name="description_it" id="description_it" style="width:100%">{{ $testimonial->description_it }}</textarea>

            </div>

        </div>
            
            
         

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">

              <button type="submit" class="btn btn-primary-edit" style="width: 100px; height: 40px;">Submit</button>

            </div>

        </div>

   

    </form>

@endsection

resources/views/testimonials/index.blade.php
@extends('layouts.admin')

 
 
@section('content')

    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Testimonials</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-success" href="{{ route('testimonials.create') }}"> Create New Testimonial</a>

            </div>

        </div>

    </div>

   

    @if ($message = Session::get('success'))

        <div class="alert alert-success">

            <p>{{ $message }}</p>

        </div>

    @endif

   

    <table class="table table-bordered">

        <tr>


            <th>Testimonial (English)</th>
            
            <th>Testimonial (France)</th>
            
            <th>Designation</th>
            <th>Thumbnail</th>

            
            <th>Created Date</th>
            

            <th>Action</th>

        </tr>

        @foreach ($testimonials as $testimonial)

        <tr>


            <td>{{ $testimonial->description_en }}</td>

            <td>{{ $testimonial->description_fr }}</td>
            
            <td>{{ $testimonial->testimonial_location_en }}</td>
            <td>
			 
			@if($testimonial->thumbnail !='')
				<img src="{{asset('public/images/')}}/{{$testimonial->thumbnail}}" style="max-height:50px;" />
			@endif
			</td>
            
            
            
            <td>{{date('m-d-Y', strtotime($testimonial->created_on))}}</td>
            
             

            <td> 

                <form action="{{ route('testimonials.destroy',$testimonial->id) }}" method="POST">
 
   


    

                    <a  class="btn btn-success" href="{{ route('testimonials.edit',$testimonial->id) }}">Edit</a>

   

                    @csrf

                    @method('DELETE')

      

                    <button type="submit" class="btn btn-danger">Delete</button>

                </form>

            </td>

        </tr>

        @endforeach

    </table>

  

 {!! $testimonials->links() !!}

      

@endsection

resources/views/testimonials/show.blade.php
@extends('categories.layout')


@section('content')

    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2> Show Category</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('categories.index') }}"> Back</a>

            </div>

        </div>

    </div>

   

    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (En):</strong>

                {{ $category->name_en }}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (Fr):</strong>

                {{ $category->name_fr }}

            </div>

        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name (Sp):</strong>

                {{ $category->name_sp }}

            </div>

        </div>
        
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Type:</strong>

                {{ $category->type }}

            </div>

        </div>

    </div>

@endsection