routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/* set language for site starts here   */
Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale); 
    return redirect()->back();
});

/* set language for site ends here   */

Route::post('ckeditor/image_upload', 'CKEditorController@upload')->name('upload');

Route::get('/', 'MainController@index');

Route::get('admin/file-upload', 'EbookController@create');
Route::post('admin/file-upload/upload', 'EbookController@upload')->name('upload');
Route::post('admin/file-upload/store', 'EbookController@store');
Route::post('admin/file-upload/storecoverimagepdf', 'EbookController@storecoverimagepdf');
Route::post('admin/file-upload/update', 'EbookController@update'); 

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/changePassword','HomeController@showChangePasswordForm');
Route::post('/changePassword','HomeController@changePassword')->name('changePassword');


Route::get('about', 'CmsController@about');
Route::get('careers', 'CmsController@careers');
Route::get('testimonials', 'CmsController@testimonials');
Route::get('terms', 'CmsController@terms');
Route::get('privacy-policy', 'CmsController@privacy');
Route::get('help', 'CmsController@help');
Route::get('benefits', 'CmsController@benefits');
Route::get('refund-policy', 'CmsController@refund_policy');
Route::get('thank-you', 'CmsController@thank_you');


Route::get('/contact', 'ContactController@index');
Route::post('/contact', 'ContactController@store');


Route::get('/subscribe', 'SubscribeController@index')->name('subscribe');
Route::get('/subscribe-membership','SubscribeController@buyMembership');
Route::get('/subscribe-membership2','SubscribeController@buyMembership2');
Route::post('/subscribe-membership','SubscribeController@buyMembershipPost')->name('subscribe-membership');

  
Route::get('/', function () {
    return view('home');
});
Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
	Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
    Route::get('/home', 'AdminController@index')->name('admin.home');
	
	Route::resource('/users','UserController'); 
	Route::resource('/categories','CategoryController'); 
	Route::resource('/faqs','FaqController'); 
	Route::resource('/features','FeaturesController'); 
	Route::resource('/testimonials','TestimonialController');
	Route::resource('/tags','TagController');  
	Route::resource('/contents','ContentController'); 
	Route::resource('/seos','SeoController');  
	
	Route::resource('/subscribers','UserController'); 
	Route::get('/active/subscribers', 'UserController@showsubscribers_active');
	Route::get('/inactive/subscribers', 'UserController@showsubscribers_inactive');
	Route::get('subscriber_remove/{subscriber_id}','UserController@subscriber_remove');
	Route::get('inactive_subscriber_view/{subscriber_id}','UserController@inactive_subscriber_view');
	Route::get('active_subscriber_view/{subscriber_id}','UserController@active_subscriber_view');
	Route::any('/active/subscribers/change_password','UserController@change_password');
	Route::resource('/ebooks','EbookController'); 

});

Route::get('/logout',[
        'uses' => 'MainController@logout', 
        'as'   => 'logout'
        ]);
Route::get('/cancel-account', 'MainController@cancel_account');
Route::post('/cancel-account','MainController@store')->name('cancel-account');

/*Route::get('/pricing', 'MainController@pricing');
Route::post('/pricing', 'MainController@pricing_post');*/



/*Route::get('/pricing-step2', 'MainController@index')->name('pricing_step2');
Route::get('/pricing-step2','MainController@pricing_step2');
Route::post('/pricing-step2','MainController@pricing_post_step2')->name('pricing_step2');
*/
Route::get('pricing','MainController@pricing_step1');
Route::get('/pricing-step2/{plan_id}','MainController@pricing_step2');
Route::post('/pricing-step2', 'MainController@pricing_post')->name('pricing_step2');
Route::get('/', ['as'=>'home', 'uses'=>'MainController@home']);


Route::get('/view-profile','MainController@view_profile');
Route::post('/view-profile', 'MainController@update_profile')->name('update_profile');
Route::get('books','CatController@showallcategory');
Route::get('bookcategory/{category_id}','CatController@show');
Route::get('ebookview/{book_id}','CatController@ebookview');
Route::get('ebookpreview/{book_id}','PreviewController@ebookpreview');

Route::get('ebookpreview2','PreviewController@ebookpreview2');

/*********** USER Routes ************/


Route::get('dashboard','DashboardController@index');

/*********** Accounts route **********/
Route::get('accounts','AccountsController@index');
Route::get('accounts/add','AccountsController@add');
Route::post('accounts/save','AccountsController@save');
Route::get('delete_account/{id}','AccountsController@delete_account');
Route::get('show_account/{id}','AccountsController@show');
Route::get('show_account/{id}/{all}','AccountsController@show');

Route::resource('accounts','AccountsController');

/*********** Budgets route **********/

Route::get('budgets/add','BudgetsController@add');
Route::post('budgets/save','BudgetsController@save');
Route::get('budgets/show/{id}','BudgetsController@show');
Route::get('budgets/show/{id}/{all}','BudgetsController@show');

Route::get('delete_budget/{id}','BudgetsController@delete_budget');
Route::resource('budgets','BudgetsController');

/*********** Categories route **********/
Route::get('categories/add','CategoriesController@add');
Route::post('categories/save','CategoriesController@save');
Route::get('categories/show/{id}','CategoriesController@show');
Route::get('categories/show/{id}/{all}','CategoriesController@show');

 

Route::get('delete_category/{id}','CategoriesController@delete_category');
Route::resource('categories','CategoriesController');

/*********** Liabilities route **********/
Route::get('liabilities','LiabilitiesController@index');
Route::get('liabilities/add','LiabilitiesController@add');
Route::post('liabilities/save','LiabilitiesController@save');
Route::get('liabilities/show/{id}','LiabilitiesController@show');
Route::get('liabilities/show/{id}/{all}','LiabilitiesController@show');

 
Route::resource('liabilities','LiabilitiesController');
Route::get('remove_liability/{id}','LiabilitiesController@remove_liability');

/*********** Transactions route **********/
Route::get('transactions','TransactionsController@index');
Route::post('transactions','TransactionsController@index');
Route::get('transations/add','TransactionsController@add');
Route::get('repeat_option/{id}','TransactionsController@repeat_option');

Route::get('transations/show/{id}','TransactionsController@show');

Route::get('repeat_month_day/{id}','TransactionsController@repeat_month_day');
Route::get('clone_transaction/{id}','TransactionsController@clone_transaction');
Route::get('stop_repeated_transections/{id}','TransactionsController@stop_repeated_transections');
Route::get('remove_transaction/{id}','TransactionsController@remove_transaction');
Route::post('transactions/save','TransactionsController@save');
Route::post('transactions/search','TransactionsController@search');
 
Route::resource('transactions','TransactionsController');
//Route::resource('/categories','CategoryController'); 
 
Auth::routes();

 

/******************************/
Route::get('budget_cron','CronController@manage_budgets');
Route::get('create_transection','CronController@create_transection');
 

/* language translator manager url rewriting starts here */
Route::get('/admin/translations/view/{groupKey?}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@getView']);
Route::get('/admin/translations/{groupKey?}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@getIndex']);
Route::post('/admin/translations/add/{groupKey}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postAdd']);
Route::post('/admin/translations/edit/{groupKey}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postEdit']); 
Route::post('/admin/translations/delete/{groupKey}/{translationKey}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postDelete']);
Route::post('/admin/translations/import',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postImport']);
Route::post('/admin/translations/find',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postFind']);
Route::post('/admin/translations/locales/add',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postAddLocale']);
Route::post('/admin/translations/locales/remove',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postRemoveLocale']);
Route::post('/admin/translations/publish/{groupKey}',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postPublish']);
Route::post('/admin/translations/translate-missing',['middleware' => ['auth:admin'],'uses' =>'\Barryvdh\TranslationManager\Controller@postTranslateMissing']);
Route::post('/admin/translations/groups/add','\Barryvdh\TranslationManager\Controller@postAddGroup');

/* language translator manager url rewriting ends here */

app/Http/Controllers/UserController.php
<?php

  

namespace App\Http\Controllers;

  

use App\User; 

use Auth;

use DB; 

use Illuminate\Support\Facades\Hash;

use Illuminate\Http\Request;

  

class UserController extends Controller

{
 
    /**

     * Display a listing of the resource.

     *

     * @return \Illuminate\Http\Response

     */
	 private $apiKey; 
	 
	  
	public function __construct()
    {
	
		 
		  
         $this->middleware('auth:admin'); 
    }
	
    public function index()

    {
	 
	 	 
		if(Auth::guard('admin')->check())
		{  
	 	
		$users = \DB::table('users')
    ->select(
        'users.id',
        'name',
		'email',
		'created_at'
    )
    ->whereNotExists( function ($query){
        $query->select(DB::raw(1))
        ->from('user_membership')
        ->whereRaw('users.id = user_membership.user_id');
    })->orderBy('users.id', 'desc')->paginate(10);
	
	 
	
	 
 		 
 
        return view('users.index',compact('users'))
			->with(['MainTitle'=>$this->apiKey])
            ->with('i', (request()->input('page', 1) - 1) * 5);
		}
		else
		{
		return redirect('admin/login');
		}

    }
	
	
	public function subscriber_remove($subscriber_id)
	{
	
	$unsubscribe_date=date("Y-m-d H:i:s");
	DB::table('user_membership')
			->where('id', $subscriber_id)
			->update([
				'status' => 'inactive',
				'unsubscribe_date' => $unsubscribe_date
			
			]
			);
	return redirect()->action('UserController@showsubscribers_active')->with('success', 'User  unsubscribed successfully!!!');
 	}
	
	
	public function inactive_subscriber_view($subscriber_id)
	{
	
	 $subscribers = DB::select("select * from users left join user_membership on  user_membership.user_id=users.id   where user_membership.id=".$subscriber_id." order by users.id desc");
	 $countrydata = DB::select('select * from apps_countries ');
	 return view('users.viewinactive',['user'=>$subscribers[0],'countrydata'=>$countrydata]);
	//return redirect()->action('UserController@showsubscribers_active')->with('success', 'User  unsubscribed successfully!!!');
 	}
	
	public function active_subscriber_view($subscriber_id) 
	{
	
	 $subscribers = DB::select("select * from users left join user_membership on  user_membership.user_id=users.id   where user_membership.id=".$subscriber_id." order by users.id desc");
 	 $countrydata = DB::select('select * from apps_countries ');
	 return view('users.viewactive',['user'=>$subscribers[0],'countrydata'=>$countrydata,'subscriber_id'=>$subscriber_id]);
	//return redirect()->action('UserController@showsubscribers_active')->with('success', 'User  unsubscribed successfully!!!');
 	}
	
	public function showsubscribers_active()

    { 
	 
	 	 
		if(Auth::guard('admin')->check())
		{  
	 	
		 
		$subscribers = DB::table('users')
                ->join('user_membership', 'user_id', '=', 'users.id')
				->where('user_membership.status', '=', 'active')
                ->select('users.*', 'user_membership.*')
                ->orderby('users.id', 'desc')
                ->paginate(10);
		 
		 
 
        return view('users.activesubscribers',compact('subscribers'))
			->with(['MainTitle'=>$this->apiKey])
            ->with('i', (request()->input('page', 1) - 1) * 5);
		}
		else
		{
		return redirect('admin/login');
		}

    }
	
	
	public function showsubscribers_inactive()

    {
	 
	 	 
		if(Auth::guard('admin')->check())
		{  
	 	
		 
		$subscribers = DB::table('users')
                ->join('user_membership', 'user_id', '=', 'users.id')
				->where('user_membership.status', '=', 'inactive')
                ->select('users.*', 'user_membership.*')
				->orderby('users.id', 'desc')
                ->paginate(10);
		 
		 
		 
 
        return view('users.inactivesubscribers',compact('subscribers'))
			->with(['MainTitle'=>$this->apiKey])
            ->with('i', (request()->input('page', 1) - 1) * 5);
		}
		else
		{
		return redirect('admin/login');
		}

    }

   

    /**

     * Show the form for creating a new resource.

     *

     * @return \Illuminate\Http\Response

     */

    public function create()

    {

        return view('users.create');

    }

  

    /**

     * Store a newly created resource in storage.

     *

     * @param  \Illuminate\Http\Request  $request

     * @return \Illuminate\Http\Response

     */
	public function change_password()
	{
	 
		if($_POST['password']!="")
		{
		$trackings = DB::select("select * from user_membership where id=".$_POST['subscriber_id']."");
		$user_id=$trackings[0]->user_id;
				DB::table('users')
				->where('id', $user_id) 
				->update([
					'password' => Hash::make($_POST['password'])
				
				]
				);
		return redirect()->action('UserController@active_subscriber_view', ['subscriber_id' => $_POST['subscriber_id']])->with('success', 'Password changes successfully!!!');	
		}
		else
		{
		return redirect()->action('UserController@active_subscriber_view', ['subscriber_id' => $_POST['subscriber_id']]);	
		}	
	}
    public function store(Request $request)

    {

        $request->validate([

            'name' => 'required',

            'email' => 'required',
			
			'password' => 'required',
			

        ]);

 		$created_on=date("Y-m-d H:i:s");
		
		 User::create([
            'name' => $request['name'],
            'email' => $request['email'],
            'password' => Hash::make($request['password']),
        ]);
        

   

        return redirect()->route('users.index')

                        ->with('success','Users created successfully.');

    }

   

    /**

     * Display the specified resource.

     *

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function show(User $user)

    {

        return view('users.show',compact('user'));

    }

   

    /**

     * Show the form for editing the specified resource.

     *

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function edit(User $user)

    {
		
		$countrydata = DB::select('select * from apps_countries '); 	
        return view('users.edit',['user'=>$user,'countrydata'=>$countrydata]);

    }

  

    /**

     * Update the specified resource in storage.

     *

     * @param  \Illuminate\Http\Request  $request

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function update(Request $request, User $user)

    {

        $request->validate([

            'name' => 'required',

            'email' => 'required',
			

        ]);

  		

 		$user->update(array_merge($request->all(),['password' => Hash::make($_POST['password'])]));

  

        return redirect()->route('users.index')

                        ->with('success','User updated successfully');

    }

  

    /**

     * Remove the specified resource from storage.

     *

     * @param  \App\Product  $product

     * @return \Illuminate\Http\Response

     */

    public function destroy(User $user)

    {

        $user->delete();

  

        return redirect()->route('users.index')

                        ->with('success','User deleted successfully');

    }

}

resources/views/users/accounts/accounts.blade.php
@extends('layouts.app')

@section('content')

<div class="container 11">
     
</div>
<template>
<component :is="'style'">
body{background:#f6f6f6}
</component>
</template>

<div class="page dashboardpages"> 
<div class="inner-container">
<script  type="application/javascript">
var isMobile = {
    Android: function() {
        return navigator.userAgent.match(/Android/i);
    },
    BlackBerry: function() {
        return navigator.userAgent.match(/BlackBerry/i);
    },
    iOS: function() {
        return navigator.userAgent.match(/iPhone|iPad|iPod/i);
    },
    Opera: function() {
        return navigator.userAgent.match(/Opera Mini/i);
    },
    Windows: function() {
        return navigator.userAgent.match(/IEMobile/i);
    },
    any: function() {
        return (isMobile.Android() || isMobile.BlackBerry() || isMobile.iOS() || isMobile.Opera() || isMobile.Windows());
    }
};

if(isMobile.any()) {

	
   //some code...
   //$(".show_hide_cat_div").css("display", "none");
   
 
    
     $(document).on('click', '#cat_title_ebook', function(event){
 			
 			 
  			$('.show_hide_cat_div').toggleClass("hideCatClass"); 
 			
      		event.stopImmediatePropagation();
	});
     
}
 

</script>
 			 
		<div class="category-sidebar">
		 @include('layouts.sidebar')
		 </div>
		<div class="category innerright-side">
				<div class="page-title">
				<h1> 
				@if($title!="")                 
				{{ $title }}
				 @endif  
				 </h1><a class="btn btn-success purple-btn" href="{{ env('APP_URL') }}accounts/add">{!!html_entity_decode(__('accounts.add_account'))!!}</a></div>
                 
                 <div class="dashborad-about"> 
					<p>{!!html_entity_decode(__('accounts.listing_heading_text'))!!}</p>			 
				  @include('flash-message')
				 </div>
                 <div class="dashboard-recenttable">
                 <div id="no-more-tables">
                 <table class="table table-bordered">
		<thead>
        <tr>


            <th>{!!html_entity_decode(__('accounts.Name'))!!} </th>
			<th>{!!html_entity_decode(__('accounts.current_balance'))!!}</th>
			<th>{!!html_entity_decode(__('accounts.status'))!!}</th>
			<th>{!!html_entity_decode(__('accounts.Action'))!!}</th>

        </tr>
			</thead>
        @foreach ($accounts as $account)

        <tr>


            <td data-title="{!!html_entity_decode(__('accounts.Name'))!!}"><a href="{{ env('APP_URL') }}show_account/{{$account->id }}">{{ $account->title }}</a></td>
			<td data-title="{!!html_entity_decode(__('accounts.current_balance'))!!}">{!!html_entity_decode(__('common.currency_symbol'))!!}{{ $account->balance }} </td>
			<td data-title="{!!html_entity_decode(__('accounts.status'))!!}">{{ $account->is_active==1?'Active':'Inactive' }}</td>
            
            <td data-title="{!!html_entity_decode(__('accounts.Action'))!!}"> 
			
			
			<a  class="btn btn-success editicon" href="{{ route('accounts.edit',$account->id) }}">{!!html_entity_decode(__('accounts.edit'))!!}</a>
			<a class="btn btn-success deleteicon" onclick="return confirm('{!!html_entity_decode(__('accounts.delete_confirm'))!!}')" href="{{ env('APP_URL') }}delete_account/{{$account->id }}">{!!html_entity_decode(__('accounts.delete'))!!}</a>
			 

            </td>

        </tr>

        @endforeach

    </table>
    </div>
								 </div>
				 
		</div> 
    			 
    
   
    
    <div class="clear"></div>
    </div>
     <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</div>
@endsection
 

resources/views/users/accounts/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container 11">
     
</div>
<template>
<component :is="'style'">
body{background:#f6f6f6}
</component>
</template>

<div class="page dashboardpages"> 
<div class="inner-container">
<script  type="application/javascript">
var isMobile = {
    Android: function() {
        return navigator.userAgent.match(/Android/i);
    },
    BlackBerry: function() {
        return navigator.userAgent.match(/BlackBerry/i);
    },
    iOS: function() {
        return navigator.userAgent.match(/iPhone|iPad|iPod/i);
    },
    Opera: function() {
        return navigator.userAgent.match(/Opera Mini/i);
    },
    Windows: function() {
        return navigator.userAgent.match(/IEMobile/i);
    },
    any: function() {
        return (isMobile.Android() || isMobile.BlackBerry() || isMobile.iOS() || isMobile.Opera() || isMobile.Windows());
    }
};

if(isMobile.any()) {

	
   //some code...
   //$(".show_hide_cat_div").css("display", "none");
   
 
    
     $(document).on('click', '#cat_title_ebook', function(event){
 			
 			 
  			$('.show_hide_cat_div').toggleClass("hideCatClass"); 
 			
      		event.stopImmediatePropagation();
	});
     
}
 

</script>
 			 
		<div class="category-sidebar">
		 @include('layouts.sidebar')
		 </div>
		<div class="category innerright-side">

				<div class="page-title">
                <h1>{!!html_entity_decode(__('accounts.edit_account'))!!}</h1>
  
               <a class="btn btn-success purple-btn" href="{{ route('accounts.index') }}"> {!!html_entity_decode(__('accounts.back'))!!}</a>
     </div>
			<div class="dashborad-about">
			<p>{!!html_entity_decode(__('accounts.edit_heading_text'))!!}</p>
  </div>
 
 <div class="dashboard-form">	
    <form action="{{ route('accounts.update',$account->id) }}" method="POST" enctype="multipart/form-data" autocomplete="off">

        @csrf

        @method('PUT')

   

         <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>{!!html_entity_decode(__('accounts.Name'))!!} : <span class="red">*</span></strong>
				<input type="hidden" name="id" value="{{$account->id}}" />
                <input type="text" name="title" class="form-control"  value="{{ $account->title }}" pattern=".*\S+.*" />

            </div>

        </div>
        
         
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>{!!html_entity_decode(__('accounts.account_type'))!!} : <span class="red">*</span></strong>

                <select name="account_type" class="form-control">
					@foreach ($account_types as $key => $val)
						<option value="{{ $val->name }}" {{ ( $val->name == $account->account_type) ? 'selected' : '' }} >
						{{ $val->name}}</option>
					@endforeach
					</select>


            </div>

        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>{!!html_entity_decode(__('accounts.opening_balance'))!!} {!!html_entity_decode(__('common.currency_symbol'))!!} : </strong>

                <input type="number" readonly name="opening_balance" class="form-control"  min="0" value="{{ $account->balance }}">

            </div>

        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Account Role :</strong>

               <select name="account_role" class="form-control">
					@foreach ($account_roles as $key => $value)
						<option value="{{ $value->name }}"
						@if ( $value->name == $account->account_role)
							selected="selected"
						@endif
						>
						{{ $value->name}}</option>
					@endforeach
					</select>

            </div>

        </div>
 
 
        
        
        
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>{!!html_entity_decode(__('accounts.Description'))!!} :</strong>

                <textarea name="description" id="description" style="width:100%">{{ $account->description }}</textarea>

            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

              <button type="submit" class="btn btn-primary-edit purple-btn" style="width: 100px; height: 40px;">{!!html_entity_decode(__('accounts.submit'))!!}</button>

            </div>

        </div>

   

    </form>
</div>
</div> 
    			 
    
   
    
    <div class="clear"></div>
    </div>
</div>
@endsection
 

resources/views/users/accounts/form.blade.php
    <form action="{{ route('accounts.update',$account->id) }}" method="POST" enctype="multipart/form-data" autocomplete="off">
        @csrf
        @method('PUT')
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
				<input type="hidden" name="id" value="{{$account->id}}" />
                <input type="text" name="title" class="form-control"  value="{{ $account->title }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Account Type:</strong>
                <select name="account_type">
					@foreach ($account_types as $key => $val)
						<option value="{{ $val->name }}" {{ ( $val->name == $account->account_type) ? 'selected' : '' }} >
						{{ $val->name}}</option>
					@endforeach
					</select>
            </div>
        </div>
         <div class="col-xs-12 col-sm-12 col-md-12">
           <div class="form-group">
                <strong>Opening balance</strong>
               <input type="text" name="opening_balance" class="form-control"  value="{{ $account->opening_balance }}">

            </div>

        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Account Role:</strong>

               <select name="account_role">
					@foreach ($account_roles as $key => $value)
						<option value="{{ $value->name }}"
						@if ( $value->name == $account->account_role)
							selected="selected"
						@endif
						>
						{{ $value->name}}</option>
					@endforeach
					</select>

            </div>

        </div>
         <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description:</strong>

                <textarea name="description" id="description" style="width:100%">{{ $account->description }}</textarea>

            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

              <button type="submit" class="btn btn-primary-edit" style="width: 100px; height: 40px;">Submit</button>

            </div>

        </div>

    </form>